pr: none

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*

pool:
  vmImage: ubuntu-18.04

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '5.0.100-rc.1.20452.10'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet test --configuration Release --logger trx --collect "XPlat code coverage"
  displayName: dotnet test

- task: PublishTestResults@2
  displayName: Publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)/test/TestResults/**/coverage.cobertura.xml