trigger: none
pr: none

pool:
  # docFX on Ubuntu throws a null reference exception
  vmImage: windows-latest

steps:
  - script: choco install docfx
  - bash: make docs
  - publish: docs/docfx/_site
    artifact: Docs