trigger: none
pr: none

pool:
  # docFX on AzP's Ubuntu throws a null reference exception
  vmImage: windows-latest

steps:
  - task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '2.2.401' # required by Coverlet
    installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore
  - script: choco install docfx
  - bash: make docs
  - publish: docs/docfx/_site
    artifact: Docs