trigger: none
pr: none

pool:
  # docFX on AzP's Ubuntu throws a null reference exception
  vmImage: windows-latest

steps:
  - script: choco install docfx
  - script: dotnet restore
  - bash: make docs
  - publish: docs/docfx/_site
    artifact: Docs