pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '5.0.100'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet pack --configuration Release
  displayName: dotnet pack

- script: dotnet nuget push src/bin/Release/RecoreFX.$VERSION.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
  displayName: dotnet nuget push
  env:
    NUGET_API_KEY: $(NUGET_API_KEY)