pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

pool:
  vmImage: vs2017-win2016

steps:
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core SDK
  inputs:
    version: '>= 2.2.300' # required by Coverlet

- script: dotnet build --configuration Release
  displayName: dotnet build

- script: dotnet test --configuration Release --logger trx --collect "XPlat code coverage"
  displayName: dotnet test

- task: PublishTestResults@2
  displayName: Publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)/test/TestResults/**/coverage.cobertura.xml