trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

strategy:
  matrix:
    Linux:
      vmImage: ubuntu-16.04
    MacOS:
      vmImage: macOS-10.13
    Windows:
      vmImage: vs2017-win2016

pool:
  vmImage: $[ variables.vmImage ]

steps:
# You can't `dotnet test` on a solution file correctly before 2.1.5
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.503'
  displayName: Install .NET Core SDK 2.1.503

- script: cd src && dotnet build --configuration Release
  displayName: dotnet build

- script: cd src && dotnet test --configuration Release --logger trx
  displayName: dotnet test

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: Publish test results
