trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

jobs:
- template: azure-pipelines/hosted-job.yml
  parameters:
    vmImage: vs2017-win2016

- template: azure-pipelines/hosted-job.yml
  parameters:
    vmImage: ubuntu-16.04

- template: azure-pipelines/hosted-job.yml
  parameters:
    vmImage: macOS-10.13