name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.1.20452.10'

    - name: dotnet test
      run: dotnet test --configuration Release --logger trx --collect "XPlat code coverage"
